##############################################################
#                                                            #
#    Mark Hoogendoorn and Burkhardt Funk (2017)              #
#    Machine Learning for the Quantified Self                #
#    Springer                                                #
#    Chapter 4                                               #
#                                                            #
##############################################################

import sys
import copy
import pandas as pd
import time
from pathlib import Path
import argparse

from util.VisualizeDataset import VisualizeDataset
from Chapter4.TemporalAbstraction import NumericalAbstraction
from Chapter4.TemporalAbstraction import CategoricalAbstraction
from Chapter4.FrequencyAbstraction import FourierTransformation
from Chapter4.TextAbstraction import TextAbstraction

# Read the result from the previous chapter, and make sure the index is of the type datetime.
DATA_PATH = Path('./intermediate_datafiles_bouldering/')
DATASET_FNAME = 'chapter3_result_final_bouldering.csv'
RESULT_FNAME = 'chapter4_result_bouldering.csv'


def print_flags():
    """
    Prints all entries in FLAGS variable.
    """
    for key, value in vars(FLAGS).items():
        print(key + ' : ' + str(value))


def main():
    print_flags()

    start_time = time.time()
    try:
        dataset = pd.read_csv(DATA_PATH / DATASET_FNAME, index_col=0)
        dataset.index = pd.to_datetime(dataset.index)
    except IOError as e:
        print('File not found, try to run previous crowdsignals scripts first!')
        raise e

    # Let us create our visualization class again.
    DataViz = VisualizeDataset(__file__)

    # Compute the number of milliseconds covered by an instance based on the first two rows
    milliseconds_per_instance = (dataset.index[1] - dataset.index[0]).microseconds / 1000

    NumAbs = NumericalAbstraction()
    FreqAbs = FourierTransformation()

    # Define the consistent column names from the bouldering datasets
    # These names are derived from bouldering_ch2.py and bouldering_ch3_rest.py
    ACC_X = 'acc_X (m/s^2)'
    GYR_X = 'gyr_X (rad/s)'
    MAG_X = 'mag_X (µT)'
    LOC_HEIGHT = 'loc_Height (m)'
    PCA_1 = 'pca_1' # This column is generated by PCA in bouldering_ch3_rest.py

    if FLAGS.mode == 'aggregation':
        # Chapter 4: Identifying aggregate attributes.

        # Set the window sizes to the number of instances representing 5 seconds, 30 seconds and 5 minutes
        window_sizes = [int(float(5000) / milliseconds_per_instance),
                        int(float(0.5 * 60000) / milliseconds_per_instance),
                        int(float(5 * 60000) / milliseconds_per_instance)]

        # please look in Chapter4 TemporalAbstraction.py to look for more aggregation methods or make your own.

        for ws in window_sizes:
            # Changed 'acc_phone_x' to 'ACC_X'
            dataset = NumAbs.abstract_numerical(dataset, [ACC_X], ws, 'mean')
            # Changed 'acc_phone_x' to 'ACC_X'
            dataset = NumAbs.abstract_numerical(dataset, [ACC_X], ws, 'std')

        # Changed 'acc_phone_x' to 'ACC_X' and updated derived column names
        DataViz.plot_dataset(dataset, [ACC_X, f'{ACC_X}_temp_mean', f'{ACC_X}_temp_std', 'label'],
                             ['exact', 'like', 'like', 'like'], ['line', 'line', 'line', 'points'])
        print("--- %s seconds ---" % (time.time() - start_time))

    if FLAGS.mode == 'frequency':
        # Now we move to the frequency domain, with the same window size.

        fs = float(1000) / milliseconds_per_instance
        ws = int(float(10000) / milliseconds_per_instance)
        # Changed 'acc_phone_x' to 'ACC_X'
        dataset = FreqAbs.abstract_frequency(dataset, [ACC_X], ws, fs)
        # Spectral analysis.
        # Changed 'acc_phone_x_max_freq', 'acc_phone_x_freq_weighted', 'acc_phone_x_pse' to use ACC_X
        DataViz.plot_dataset(dataset, [f'{ACC_X}_max_freq', f'{ACC_X}_freq_weighted', f'{ACC_X}_pse', 'label'],
                             ['like', 'like', 'like', 'like'], ['line', 'line', 'line', 'points'])
        print("--- %s seconds ---" % (time.time() - start_time))

    if FLAGS.mode == 'final':
        ws = int(float(0.5 * 60000) / milliseconds_per_instance)
        fs = float(1000) / milliseconds_per_instance

        # We need to get all numerical columns excluding 'label' for abstraction.
        # The 'label' column itself is not a numerical predictor.
        selected_predictor_cols = [c for c in dataset.columns if not 'label' in c]

        dataset = NumAbs.abstract_numerical(dataset, selected_predictor_cols, ws, 'mean')
        dataset = NumAbs.abstract_numerical(dataset, selected_predictor_cols, ws, 'std')
        # TODO: Add your own aggregation methods here

        # Adjusted plot_dataset to use appropriate columns from bouldering dataset.
        # Removed 'hr_watch_rate', 'light_phone_lux', 'press_phone_' as they are not in the bouldering data.
        DataViz.plot_dataset(dataset, [ACC_X, GYR_X, MAG_X, LOC_HEIGHT, PCA_1, 'label'],
                             ['like', 'like', 'like', 'like', 'like', 'like'],
                             ['line', 'line', 'line', 'line', 'line', 'points'])

        CatAbs = CategoricalAbstraction()

        dataset = CatAbs.abstract_categorical(dataset, ['label'], ['like'], 0.03,
                                              int(float(5 * 60000) / milliseconds_per_instance), 2)

        # Updated periodic_predictor_cols to match the full list from bouldering_ch2.py and bouldering_ch3_rest.py
        periodic_predictor_cols = ['acc_X (m/s^2)', 'acc_Y (m/s^2)', 'acc_Z (m/s^2)',
                                   "gyr_X (rad/s)","gyr_Y (rad/s)","gyr_Z (rad/s)",
                                   "mag_X (µT)","mag_Y (µT)","mag_Z (µT)"]
        # 'loc_Height (m)' and 'loc_Velocity (m/s)' are typically not used for Fourier Transform in this context,
        # so they are excluded from periodic_predictor_cols to align with typical usage.

        dataset = FreqAbs.abstract_frequency(copy.deepcopy(dataset), periodic_predictor_cols,
                                             int(float(10000) / milliseconds_per_instance), fs)

        # Now we only take a certain percentage of overlap in the windows, otherwise our training examples will be too much alike.

        # The percentage of overlap we allow
        window_overlap = 0.9
        skip_points = int((1 - window_overlap) * ws)
        dataset = dataset.iloc[::skip_points, :]

        dataset.to_csv(DATA_PATH / RESULT_FNAME)

        # Adjusted plot_dataset to use appropriate columns from bouldering dataset, same as above.
        DataViz.plot_dataset(dataset, [ACC_X, GYR_X, MAG_X, LOC_HEIGHT, PCA_1, 'label'],
                             ['like', 'like', 'like', 'like', 'like', 'like'],
                             ['line', 'line', 'line', 'line', 'line', 'points'])
        print("--- %s seconds ---" % (time.time() - start_time))


if __name__ == '__main__':
    # Command line arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('--mode', type=str, default='final',
                        help="Select what version to run: final, aggregation or freq \
                        'aggregation' studies the effect of several aggeregation methods \
                        'frequency' applies a Fast Fourier transformation to a single variable \
                        'final' is used for the next chapter ", choices=['aggregation', 'frequency', 'final'])

    FLAGS, unparsed = parser.parse_known_args()

    main()